argocd:
  enabled: true
  syncwave: "1"

backend:
  name: "Globex Order Placement Backend"
  systemName: "globex-order-placement-backend"
  privateBaseURL: "http://order-placement.globex-user1.svc.cluster.local:8080"