argocd:
  enabled: true
  syncwave: "2"

activedoc:
  name: "Globex Order Placement ActiveDoc 1.1.0"
  systemName: globex-order-placement-activedoc-1-1-0
  issuerEndpoint: ""


product:
  systemName: globex-order-placement-product

activeDocOpenAPIRef:
  url: "https://raw.githubusercontent.com/rh-soln-pattern-api-versioning/api-spec/main/v1.1/OrderPlacementAPI-V1.1.yaml"