apiVersion: capabilities.3scale.net/v1beta1
kind: DeveloperAccount
metadata:
  name: globex-developeraccount
  annotations:
    {{- include "globex-dev-account.developeraccount.argocd-syncwave" . | nindent 4 }}
spec:
  orgName: Globex
  providerAccountRef:
    name: 3scale-tenant-secret