apiVersion: v1
kind: Secret
metadata:
  name: globexuser.secret
  annotations:
    {{- include "globex-dev-account.secret.argocd-syncwave" . | nindent 4 }}
type: Opaque
stringData:
  password: openshift
