apiVersion: capabilities.3scale.net/v1beta1
kind: Backend
metadata:
  name: {{ include "order-placement-backend.name" . }}
  annotations:
    {{- include "order-placement-backend.argocd-syncwave" . | nindent 4 }}
spec:
  name: Order Placement Backend V1.0.0
  systemName: order-placement-backend-V-1-0-0
  privateBaseURL:  http://order-placement.globex-user1.svc.cluster.local:8080
  providerAccountRef:
    name: 3scale-tenant-secret
  metrics:
    hits:
      description: Number of API hits
      friendlyName: Hits
      unit: "hit"
  mappingRules:
    - httpMethod: POST
      pattern: "/"
      increment: 1
      metricMethodRef: hits
