apiVersion: capabilities.3scale.net/v1beta1
kind: ActiveDoc
metadata:
  name: {{ include "globex-activedoc-2-0-0.name" . }}
  annotations:
    {{- include "globex-activedoc-2-0-0.argocd-syncwave" . | nindent 4 }}
spec:
  activeDocOpenAPIRef:
    url: {{ .Values.activeDocOpenAPIRef.url }}
  published: true
  name: {{ .Values.activedoc.name }}
  providerAccountRef:
    name: 3scale-tenant-secret
  productSystemName: {{ .Values.product.systemName }}
  
