argocd:
  enabled: true
  syncwave: "2"

activedoc:
  name: "Globex Order Placement ActiveDoc"
  systemName: globex-order-placement-activedoc
  issuerEndpoint: ""


product:
  systemName: globex-order-placement-product

activeDocOpenAPIRef:
  url: "https://raw.githubusercontent.com/rh-soln-pattern-api-versioning/api-spec/main/v1.0/OrderPlacementAPI-V1.0.yaml"